# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'JazzyTest.xcworkspace'
project 'JazzyTest.xcodeproj'

abstract_target 'Apps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JazzyTest
  pod 'CoreBluetoothMock'
  target 'JazzyTest' do
    project 'JazzyTest.xcodeproj'
    pod 'MSAL'

    target 'JazzyTestTests' do
      pod 'CoreBluetoothMock'
      # Pods for testing
    end
  end

  target 'JazzyTestUITests' do
    # Pods for testing
  end

end
